<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Fledging success – Warmer springs and reproductive performance in the collared flycatcher</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Warmer springs and reproductive performance in the collared flycatcher</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./climate_window.html"> 
<span class="menu-text">Thermal window and temperature data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data_preparation.html"> 
<span class="menu-text">Data and study population</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./model_structure.html"> 
<span class="menu-text">Model structure</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./clutch_size.html"> 
<span class="menu-text">Clutch size</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./fledging_success.html" aria-current="page"> 
<span class="menu-text">Fledging success</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./figure_code.html"> 
<span class="menu-text">Figure code</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#data" id="toc-data" class="nav-link active" data-scroll-target="#data"><span class="header-section-number">1</span> Data</a></li>
  <li><a href="#beta-binomial-model-structure" id="toc-beta-binomial-model-structure" class="nav-link" data-scroll-target="#beta-binomial-model-structure"><span class="header-section-number">2</span> Beta-binomial model structure</a>
  <ul class="collapse">
  <li><a href="#constant-versus-predictor-dependent-precision" id="toc-constant-versus-predictor-dependent-precision" class="nav-link" data-scroll-target="#constant-versus-predictor-dependent-precision"><span class="header-section-number">2.1</span> Constant versus predictor-dependent precision</a></li>
  </ul></li>
  <li><a href="#main-beta-binomial-location-scale-model" id="toc-main-beta-binomial-location-scale-model" class="nav-link" data-scroll-target="#main-beta-binomial-location-scale-model"><span class="header-section-number">3</span> Main beta-binomial location-scale model</a></li>
  <li><a href="#between-year-and-between-female-variation" id="toc-between-year-and-between-female-variation" class="nav-link" data-scroll-target="#between-year-and-between-female-variation"><span class="header-section-number">4</span> Between-year and between-female variation</a>
  <ul class="collapse">
  <li><a href="#fledging-success-and-spring-temperature" id="toc-fledging-success-and-spring-temperature" class="nav-link" data-scroll-target="#fledging-success-and-spring-temperature"><span class="header-section-number">4.1</span> Fledging success and spring temperature</a></li>
  <li><a href="#fledging-success-and-relative-laying-date" id="toc-fledging-success-and-relative-laying-date" class="nav-link" data-scroll-target="#fledging-success-and-relative-laying-date"><span class="header-section-number">4.2</span> Fledging success and relative laying date</a></li>
  <li><a href="#fledging-success-and-female-age" id="toc-fledging-success-and-female-age" class="nav-link" data-scroll-target="#fledging-success-and-female-age"><span class="header-section-number">4.3</span> Fledging success and female age</a></li>
  <li><a href="#changes-over-time" id="toc-changes-over-time" class="nav-link" data-scroll-target="#changes-over-time"><span class="header-section-number">4.4</span> Changes over time</a></li>
  </ul></li>
  <li><a href="#figure-data-and-reproducibility" id="toc-figure-data-and-reproducibility" class="nav-link" data-scroll-target="#figure-data-and-reproducibility"><span class="header-section-number">5</span> Figure data and reproducibility</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Fledging success</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="data" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="data"><span class="header-section-number">1</span> Data</h2>
<p>The main response is <strong>egg-to-fledging success, defined as the number of fledglings relative to the number of eggs laid</strong>. Hereafter, <em>fledging success</em> is used as shorthand for this egg-to-fledging measure; the denominator is not the number of hatched nestlings.</p>
<p>The model-ready data span 1981-2019 (39 seasons) and contain 9,790 broods from 7,132 females. Complete brood failure occurred in 2,315 broods (23.6%). All zero-fledgling broods are retained. Records after 2019 are excluded because they have not yet been validated.</p>
<p><code>rel_LD</code> is laying date minus the annual median laying date, recalculated after all restrictions defining the final fledging-model sample. It describes a female’s timing relative to other females breeding in the same season; it is not a measure of phenological mismatch. <code>temp_mean_c</code> and <code>year_c</code> retain the existing centring definitions.</p>
<p>The predictors operate at different hierarchical levels. Relative laying date is centred within season and is therefore identified primarily by comparisons among broods breeding in the same year; the model contains 9,790 brood records, with repeated observations of females accounted for by the female random intercept. Spring temperature and year vary only among seasons, so inference for these predictors is based on variation across 39 breeding seasons. Consequently, annual predictors are estimated from substantially fewer independent temporal units than within-season predictors.</p>
<p>Within-season centring separates variation in reproductive timing among females within a season from differences among seasons. In the final analytical sample, <code>rel_LD</code> was recalculated as laying date minus the annual median laying date after all analytical filters; the maximum absolute annual median was 0e+00 days (floating-point zero). The observed correlation with spring temperature was <span class="math inline">\(r\)</span> = 0.0468.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Years</th>
<th style="text-align: right;">Seasons</th>
<th style="text-align: right;">Broods</th>
<th style="text-align: right;">Females</th>
<th style="text-align: right;">Broods with zero fledglings</th>
<th style="text-align: right;">Zero broods (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1981-2019</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">9,790</td>
<td style="text-align: right;">7,132</td>
<td style="text-align: right;">2,315</td>
<td style="text-align: right;">23.6</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Reconciliation of the validated fledging series with the model-ready sample.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Sample definition</th>
<th style="text-align: right;">Broods</th>
<th style="text-align: right;">Complete failures</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Validated fledging records, 1981-2019</td>
<td style="text-align: right;">11004</td>
<td style="text-align: right;">2594</td>
</tr>
<tr class="even">
<td style="text-align: left;">After restricting to 1981-2019</td>
<td style="text-align: right;">11004</td>
<td style="text-align: right;">2594</td>
</tr>
<tr class="odd">
<td style="text-align: left;">After requiring the binary age class</td>
<td style="text-align: right;">9895</td>
<td style="text-align: right;">2355</td>
</tr>
<tr class="even">
<td style="text-align: left;">After requiring laying date for rel_LD</td>
<td style="text-align: right;">9790</td>
<td style="text-align: right;">2315</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="beta-binomial-model-structure" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="beta-binomial-model-structure"><span class="header-section-number">2</span> Beta-binomial model structure</h2>
<section id="constant-versus-predictor-dependent-precision" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="constant-versus-predictor-dependent-precision"><span class="header-section-number">2.1</span> Constant versus predictor-dependent precision</h3>
<p>Two otherwise identical beta-binomial models were compared on the full dataset, including broods with zero fledglings. This comparison asks specifically whether allowing beta-binomial precision to vary with the prespecified predictors improves the model of fledging success.</p>
<div class="cell">
<div class="code-with-filename">
<details class="code-fold">
<summary>Show model call</summary>
<div class="code-with-filename-file">
<pre><strong>R/30_fledging_chapter_models_figures.R</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>m_bb_constant <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(fledged, clutch <span class="sc">-</span> fledged) <span class="sc">~</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    rel_LD <span class="sc">*</span> age_class <span class="sc">+</span> temp_mean_c <span class="sc">+</span> year_c <span class="sc">+</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> year_f) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> female_id),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">dispformula =</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">betabinomial</span>(), <span class="at">data =</span> dat</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>m_bb_scale <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(fledged, clutch <span class="sc">-</span> fledged) <span class="sc">~</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    rel_LD <span class="sc">*</span> age_class <span class="sc">+</span> temp_mean_c <span class="sc">+</span> year_c <span class="sc">+</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> year_f) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> female_id),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">dispformula =</span> <span class="sc">~</span> rel_LD <span class="sc">+</span> temp_mean_c <span class="sc">+</span> year_c <span class="sc">+</span> age_class,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">betabinomial</span>(), <span class="at">data =</span> dat</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Beta-binomial model comparison on the complete brood sample.</caption>
<colgroup>
<col style="width: 28%">
<col style="width: 2%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">LR chi-square</th>
<th style="text-align: right;">df (LRT)</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">Delta AIC</th>
<th style="text-align: right;">Delta BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Constant precision</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">34354.20</td>
<td style="text-align: right;">34418.90</td>
<td style="text-align: right;">-17168.1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">45.407</td>
<td style="text-align: right;">16.651</td>
</tr>
<tr class="even">
<td style="text-align: left;">Predictor-dependent precision</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">34308.79</td>
<td style="text-align: right;">34402.25</td>
<td style="text-align: right;">-17141.4</td>
<td style="text-align: right;">53.407</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The predictor-dependent precision model was clearly supported over the constant-precision model (likelihood-ratio <span class="math inline">\(\chi^2_{4}\)</span> = 53.41, <span class="math inline">\(p\)</span> &lt; 0.001; <span class="math inline">\(\Delta\)</span>AIC = 45.4, <span class="math inline">\(\Delta\)</span>BIC = 16.7). It is therefore retained as the main model. This support comes from the beta-binomial response itself, not from a Gaussian model of positive fledgling counts.</p>
</section>
</section>
<section id="main-beta-binomial-location-scale-model" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="main-beta-binomial-location-scale-model"><span class="header-section-number">3</span> Main beta-binomial location-scale model</h2>
<p>The location equation contains relative laying date, age class, their interaction, spring temperature, and time, with random intercepts for year and female. The precision equation contains relative laying date, spring temperature, time, and age class. Larger <span class="math inline">\(\phi\)</span> indicates lower conditional extra-binomial heterogeneity; smaller <span class="math inline">\(\phi\)</span> indicates higher conditional extra-binomial heterogeneity. This is conditional residual heterogeneity, not total phenotypic variance.</p>
<div class="cell">
<details class="code-fold">
<summary>Load saved model</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>m_bb_scale <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"models/glmmTMB/fledging_bb_main_no_tempsd.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<details class="model-summary">
<summary>
Show complete coefficient table
</summary>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_bb_scale)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  main_coef <span class="sc">|&gt;</span> <span class="fu">select</span>(component, term, beta, SE, CI_low, CI_high, z, p, direction),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Component"</span>, <span class="st">"Term"</span>, <span class="st">"Beta"</span>, <span class="st">"SE"</span>, <span class="st">"95% CI low"</span>, <span class="st">"95% CI high"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">"z"</span>, <span class="st">"p"</span>, <span class="st">"Direction"</span>),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Location and precision coefficients from the main beta-binomial model."</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Location and precision coefficients from the main beta-binomial model.</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: left;">Term</th>
<th style="text-align: right;">Beta</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">95% CI low</th>
<th style="text-align: right;">95% CI high</th>
<th style="text-align: right;">z</th>
<th style="text-align: right;">p</th>
<th style="text-align: left;">Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">location</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.2589</td>
<td style="text-align: right;">0.0691</td>
<td style="text-align: right;">0.1234</td>
<td style="text-align: right;">0.3944</td>
<td style="text-align: right;">3.7454</td>
<td style="text-align: right;">0.0002</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">location</td>
<td style="text-align: left;">rel_LD</td>
<td style="text-align: right;">-0.0535</td>
<td style="text-align: right;">0.0060</td>
<td style="text-align: right;">-0.0652</td>
<td style="text-align: right;">-0.0418</td>
<td style="text-align: right;">-8.9794</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">location</td>
<td style="text-align: left;">age_classOLD</td>
<td style="text-align: right;">0.1045</td>
<td style="text-align: right;">0.0384</td>
<td style="text-align: right;">0.0293</td>
<td style="text-align: right;">0.1797</td>
<td style="text-align: right;">2.7248</td>
<td style="text-align: right;">0.0064</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">location</td>
<td style="text-align: left;">temp_mean_c</td>
<td style="text-align: right;">-0.2502</td>
<td style="text-align: right;">0.0654</td>
<td style="text-align: right;">-0.3785</td>
<td style="text-align: right;">-0.1220</td>
<td style="text-align: right;">-3.8250</td>
<td style="text-align: right;">0.0001</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">location</td>
<td style="text-align: left;">year_c</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">0.0063</td>
<td style="text-align: right;">-0.0123</td>
<td style="text-align: right;">0.0122</td>
<td style="text-align: right;">-0.0059</td>
<td style="text-align: right;">0.9953</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">location</td>
<td style="text-align: left;">rel_LD:age_classOLD</td>
<td style="text-align: right;">-0.0186</td>
<td style="text-align: right;">0.0075</td>
<td style="text-align: right;">-0.0332</td>
<td style="text-align: right;">-0.0040</td>
<td style="text-align: right;">-2.4906</td>
<td style="text-align: right;">0.0128</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">precision_log_phi</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.1293</td>
<td style="text-align: right;">0.0413</td>
<td style="text-align: right;">-0.2103</td>
<td style="text-align: right;">-0.0483</td>
<td style="text-align: right;">-3.1301</td>
<td style="text-align: right;">0.0017</td>
<td style="text-align: left;">lower phi: higher conditional heterogeneity</td>
</tr>
<tr class="even">
<td style="text-align: left;">precision_log_phi</td>
<td style="text-align: left;">rel_LD</td>
<td style="text-align: right;">-0.0229</td>
<td style="text-align: right;">0.0043</td>
<td style="text-align: right;">-0.0313</td>
<td style="text-align: right;">-0.0145</td>
<td style="text-align: right;">-5.3259</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">lower phi: higher conditional heterogeneity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">precision_log_phi</td>
<td style="text-align: left;">temp_mean_c</td>
<td style="text-align: right;">0.0509</td>
<td style="text-align: right;">0.0220</td>
<td style="text-align: right;">0.0077</td>
<td style="text-align: right;">0.0941</td>
<td style="text-align: right;">2.3079</td>
<td style="text-align: right;">0.0210</td>
<td style="text-align: left;">higher phi: lower conditional heterogeneity</td>
</tr>
<tr class="even">
<td style="text-align: left;">precision_log_phi</td>
<td style="text-align: left;">year_c</td>
<td style="text-align: right;">0.0026</td>
<td style="text-align: right;">0.0022</td>
<td style="text-align: right;">-0.0018</td>
<td style="text-align: right;">0.0070</td>
<td style="text-align: right;">1.1380</td>
<td style="text-align: right;">0.2551</td>
<td style="text-align: left;">higher phi: lower conditional heterogeneity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">precision_log_phi</td>
<td style="text-align: left;">age_classOLD</td>
<td style="text-align: right;">0.1079</td>
<td style="text-align: right;">0.0461</td>
<td style="text-align: right;">0.0175</td>
<td style="text-align: right;">0.1982</td>
<td style="text-align: right;">2.3406</td>
<td style="text-align: right;">0.0193</td>
<td style="text-align: left;">higher phi: lower conditional heterogeneity</td>
</tr>
</tbody>
</table>
</div>
</div>
</details>
<p><strong>Create coefficient tables and prediction data.</strong> This step reads the saved model and creates the cached outputs used below.</p>
<div class="cell">
<div class="code-with-filename">
<details class="code-fold">
<summary>Show output-generation step</summary>
<div class="code-with-filename-file">
<pre><strong>R/30_fledging_chapter_models_figures.R</strong></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/30_fledging_chapter_models_figures.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</section>
<section id="between-year-and-between-female-variation" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="between-year-and-between-female-variation"><span class="header-section-number">4</span> Between-year and between-female variation</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Random-effect standard deviations and nested-model reductions in year variance for fledging success.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 66%">
<col style="width: 9%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: left;">Scale or unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Location</td>
<td style="text-align: left;">Year random-intercept SD</td>
<td style="text-align: right;">0.353</td>
<td style="text-align: left;">logit scale</td>
</tr>
<tr class="even">
<td style="text-align: left;">Location</td>
<td style="text-align: left;">Female random-intercept SD</td>
<td style="text-align: right;">0.241</td>
<td style="text-align: left;">logit scale</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Location</td>
<td style="text-align: left;">Reduction in year random-intercept variance: temperature and year</td>
<td style="text-align: right;">36.239</td>
<td style="text-align: left;">%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Location</td>
<td style="text-align: left;">Reduction in year random-intercept variance: temperature alone</td>
<td style="text-align: right;">36.240</td>
<td style="text-align: left;">%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The year random-intercept SD was 0.353 and the female random-intercept SD was 0.241, both on the logit scale. The two reduction estimates compare the year random-intercept variance with nested models that omit both seasonal predictors or retain temperature alone; they replace the previous, non-additive variance-of-the-linear-predictor shares. These quantities are not a decomposition of total phenotypic variance and are not directly comparable with <span class="math inline">\(R^2\)</span>. The precision equation contains no random year or female effects, so no analogous random-effect SD is defined for <span class="math inline">\(\phi\)</span>.</p>
<section id="fledging-success-and-spring-temperature" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="fledging-success-and-spring-temperature"><span class="header-section-number">4.1</span> Fledging success and spring temperature</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/Fig5_1_success_phi_temperature.png" class="img-fluid figure-img" width="2000"></p>
<figcaption>Population-level predictions against spring temperature from the beta-binomial model. Left: mean fledging success. Right: conditional consistency, expressed as phi. Random effects are excluded; ribbons are 95% confidence intervals and the x-axis covers the 5th-95th percentiles of observed temperature.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="figure_code.html#mean-and-consistency-against-temperature">Show the plotting code in Figure code</a>.</p>
<p>Warmer springs were associated with lower mean fledging success (<span class="math inline">\(\beta\)</span> = -0.250, 95% CI -0.378 to -0.122, <span class="math inline">\(p\)</span> &lt; 0.001) and higher precision (<span class="math inline">\(\beta_{\log\phi}\)</span> = 0.051, <span class="math inline">\(p\)</span> = 0.021). Thus, both the location and scale effects of temperature were supported: fledging success was lower but conditionally more consistent in warmer springs.</p>
</section>
<section id="fledging-success-and-relative-laying-date" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="fledging-success-and-relative-laying-date"><span class="header-section-number">4.2</span> Fledging success and relative laying date</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/Fig5_2_success_rellD_age.png" class="img-fluid figure-img" width="2000"></p>
<figcaption>Population-level predictions against relative laying date for young and old females from the beta-binomial location-scale model. Left: mean fledging success. Right: conditional consistency, expressed as phi. The precision equation contains additive effects of relative laying date and age but no interaction, so its age-specific curves have a common slope on the log-phi scale. Random effects are excluded; ribbons are 95% confidence intervals.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="figure_code.html#fledging-success-figures">Show the plotting code in Figure code</a>.</p>
<p>Relatively later females had lower fledging success. The relative-laying-date slope differed between age classes (<span class="math inline">\(\beta_{\mathrm{LD\times OLD}}\)</span> = -0.019, 95% CI -0.033 to -0.004, <span class="math inline">\(p\)</span> = 0.013). The <code>rel_LD</code> main coefficient is conditional on the reference class, <code>age_class = YOUNG</code>.</p>
<p>Conditional slopes were calculated with <code>emmeans::emtrends()</code> using the full variance-covariance matrix.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Conditional relative-laying-date slopes by age class with 95% confidence intervals.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">age_class</th>
<th style="text-align: right;">rel_LD.trend</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">asymp.LCL</th>
<th style="text-align: right;">asymp.UCL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">YOUNG</td>
<td style="text-align: right;">-0.0535</td>
<td style="text-align: right;">0.0060</td>
<td style="text-align: right;">Inf</td>
<td style="text-align: right;">-0.0652</td>
<td style="text-align: right;">-0.0418</td>
</tr>
<tr class="even">
<td style="text-align: left;">OLD</td>
<td style="text-align: right;">-0.0721</td>
<td style="text-align: right;">0.0046</td>
<td style="text-align: right;">Inf</td>
<td style="text-align: right;">-0.0810</td>
<td style="text-align: right;">-0.0631</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Log-<span class="math inline">\(\phi\)</span> decreased with relative laying date (<span class="math inline">\(\beta\)</span> = -0.023, 95% CI -0.031 to -0.014, <span class="math inline">\(p\)</span> &lt; 0.001). Thus, each one-day delay multiplied <span class="math inline">\(\phi\)</span> by 0.977 (-2.3%), indicating greater conditional extra-binomial heterogeneity at later relative laying dates.</p>
<details>
<summary>
<strong>Check of the <code>rel_LD × age_class</code> interaction in precision</strong>
</summary>
<p>Adding a <code>rel_LD × age_class</code> interaction to the precision equation provided no clear evidence of age-specific slopes (likelihood-ratio <span class="math inline">\(\chi^2_1\)</span> = 2.42, <span class="math inline">\(p\)</span> = 0.120); the models were essentially indistinguishable by AIC (<span class="math inline">\(\Delta\)</span>AIC = 0.42). The interaction coefficient was <span class="math inline">\(\beta_{\log\phi}\)</span> = -0.0137 (95% CI -0.0310 to 0.0036, <span class="math inline">\(p\)</span> = 0.120). We therefore retained the simpler additive precision model, in which the age-specific curves share a relative-laying-date slope on the log-<span class="math inline">\(\phi\)</span> scale.</p>
</details>
</section>
<section id="fledging-success-and-female-age" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="fledging-success-and-female-age"><span class="header-section-number">4.3</span> Fledging success and female age</h3>
<p>Older females had higher mean fledging success at the reference relative laying date (<span class="math inline">\(\beta\)</span> = 0.105, <span class="math inline">\(p\)</span> = 0.006) and higher precision (<span class="math inline">\(\beta_{\log\phi}\)</span> = 0.108, <span class="math inline">\(p\)</span> = 0.019). Thus, both the location and scale age effects were supported; the location coefficient is conditional on <code>rel_LD = 0</code> because the location equation contains <code>rel_LD × age_class</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/Fig5_3b_phi_age.png" class="img-fluid figure-img" width="2000"></p>
<figcaption>Model-estimated mean fledging success (left) and beta-binomial consistency (right) for young and old females at the reference relative laying date, mean spring temperature, and mean study year. Points are population-level predictions; error bars are 95% confidence intervals and random effects are excluded.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="figure_code.html#mean-and-consistency-by-female-age">Show the plotting code in Figure code</a>.</p>
</section>
<section id="changes-over-time" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="changes-over-time"><span class="header-section-number">4.4</span> Changes over time</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/Fig5_4_time_location_scale.png" class="img-fluid figure-img" width="2000"></p>
<figcaption>Temporal predictions from the beta-binomial location-scale model after accounting for spring temperature. Left: population-level conditional prediction for mean fledging success. Right: conditional consistency, expressed as phi; higher values indicate greater consistency. Spring temperature is held at its study-wide mean, random effects are excluded, and ribbons show 95% confidence intervals.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="figure_code.html#conditional-temporal-trajectories">Show the plotting code in Figure code</a>.</p>
<p>After accounting for spring temperature, there was no clear evidence of temporal change in mean egg-to-fledging success (<span class="math inline">\(\beta\)</span> = -0.0000, 95% CI -0.0123 to 0.0122, <span class="math inline">\(p\)</span> = 0.995). Reproductive consistency likewise showed no clear temporal trend (<span class="math inline">\(\beta_{\log\phi}\)</span> = 0.0026, 95% CI -0.0018 to 0.0070, <span class="math inline">\(p\)</span> = 0.255).</p>
<details>
<summary>
<strong>Appendix: checks of the temperature effect on precision</strong>
</summary>
<p>The temperature effect on <span class="math inline">\(\phi\)</span> was not explained by the changing mean or the response ceiling (constant-<span class="math inline">\(\phi\)</span> simulation: exceeded in 1.5% of replicates), and it remained positive after conditioning on broods with at least one fledgling in a zero-truncated beta-binomial model (<span class="math inline">\(\beta_{\log\phi}\)</span> = 0.096, 95% CI 0.019 to 0.173, <span class="math inline">\(p\)</span> = 0.014).</p>
<p>To assess whether the temperature effect on <span class="math inline">\(\phi\)</span> could arise mechanically because mean success moved away from the upper boundary, 200 datasets were simulated with the fitted conditional means held fixed but with constant <span class="math inline">\(\phi\)</span>. The median simulated temperature coefficient in an auxiliary precision model was 0.0002 (95% simulation interval -0.0367 to 0.0372). The corresponding observed auxiliary coefficient was 0.0488; only 1.5% of simulations were at least this large. All 200 optimisations converged without reaching parameter boundaries. This targeted check does not distinguish biological from other unmodelled sources of conditional heterogeneity.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/FigA_phi_constant_simulation.png" class="img-fluid figure-img" width="1280"></p>
<figcaption>Temperature coefficients from 200 datasets simulated with constant phi. The orange line is the observed auxiliary coefficient. This is a diagnostic figure, not a biological effect estimate.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="figure_code.html#constant-phi-simulation-diagnostic">Show the plotting code in Figure code</a>.</p>
<p>To determine whether higher <span class="math inline">\(\phi\)</span> in warmer springs was instead produced by the increased probability of complete brood failure, a correctly zero-truncated beta-binomial likelihood was fitted to the 7475 broods with at least one fledgling. The location and precision equations were jointly re-estimated, while the fitted year and female contributions were retained as offsets. The temperature coefficient in precision remained positive (<span class="math inline">\(\beta_{\log\phi}\)</span> = 0.0962, 95% CI 0.0193 to 0.1731, <span class="math inline">\(p\)</span> = 0.014). The optimisation converged without a boundary estimate. Thus, the association is not attributable solely to warmer springs producing more complete failures and leaving a more homogeneous surviving subset. It may be discussed as higher conditional residual consistency among non-failed broods, but not as evidence of a causal temperature effect or a change in total phenotypic variance.</p>
</details>
<details>
<summary>
<strong>Model adequacy for complete brood failures</strong>
</summary>
<section id="simulation-based-zero-frequency-check" class="level4" data-number="4.4.1">
<h4 data-number="4.4.1" class="anchored" data-anchor-id="simulation-based-zero-frequency-check"><span class="header-section-number">4.4.1</span> Simulation-based zero-frequency check</h4>
<p>Two simulation checks address different questions. First, 1,000 datasets were simulated with the fitted year and female random effects held fixed, directly assessing calibration for the observed groups. Second, <code>simulate.glmmTMB()</code> was used to generate new random-effect realisations from their estimated distributions, assessing unconditional calibration for hypothetical new groups. The current <code>glmmTMB</code> implementation cannot condition <code>simulate()</code> on the fitted random effects, so the conditional check was generated directly from the fitted beta-binomial means and precision values.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/Fig5_4_zero_frequency_diagnostic.png" class="img-fluid figure-img" width="1280"></p>
<figcaption>Distribution of the proportion of complete brood failures in 1,000 datasets simulated conditionally on the fitted year and female random effects. The orange vertical line is the observed proportion.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="figure_code.html#fledging-success-figures">Show the plotting code in Figure code</a>.</p>
<p>The observed frequency was 23.6%. Conditional simulations had a median of 20.2% (95% simulation interval 19.4–20.9%), whereas unconditional <code>simulate.glmmTMB()</code> simulations had a median of 25.7% (95% simulation interval 25.0–26.5%). Thus, the conditional check underpredicted zeros while the unconditional check overpredicted them. The fitted model does not reproduce the observed zero frequency exactly, but the direction of the discrepancy depends on whether inference is conditional on the observed groups or averaged over new random-effect realisations. This is a model-adequacy diagnostic, not a separate biological hypothesis test, and does not by itself justify an additional zero-inflation component.</p>
</section></details>
<!-- The realised fledgling production analysis is now maintained in
realised_fledgling_production.qmd. The archived source below is excluded
from this chapter's rendered output.

## Realised fledgling production

Absolute fledgling production is the number of fledglings produced per brood. It is analysed separately from fledging success and does not include clutch size as a covariate, because clutch size is a responsive reproductive trait and may mediate the total effect of temperature and timing.

This analysis does not contain a scale equation. Neither the Bernoulli complete-failure component nor the zero-truncated Poisson positive-count component has a freely estimated dispersion parameter. Consequently, the hurdle model addresses realised output and failure risk, not reproductive consistency; consistency is evaluated in the Gaussian clutch-size and beta-binomial fledging-success models.

### Model specification


::: {.cell filename='R/30_fledging_chapter_models_figures.R'}

```{.r .cell-code  code-fold="show"}
m_count_hurdle <- glmmTMB(
  fledged ~ rel_LD * age_class + temp_mean_c + year_c +
    (1 | year_f) + (1 | female_id),
  ziformula = ~ rel_LD + temp_mean_c + year_c + age_class,
  family = truncated_poisson(), data = dat
)
```
:::


The ordinary NB2 model is retained only as a sensitivity check because it reproduced 9.3% zero broods versus 23.6% observed; the hurdle-Poisson is the final model of realised fledgling production.

::: {.callout-note collapse="true"}
### Model diagnostics

A hurdle model was fitted to separate the probability of complete failure from the positive fledgling-count distribution. After alternative optimisation, both hurdle-NB2 and hurdle-Poisson converged with positive-definite Hessians. Their log-likelihoods were effectively identical, and the simpler hurdle-Poisson had lower AIC and BIC.


::: {.cell}
::: {.cell-output-display}


Table: Comparison of the two fitted hurdle count distributions.

|Model          | Convergence|pdHess |      AIC|      BIC|    logLik|
|:--------------|-----------:|:------|--------:|--------:|---------:|
|Hurdle NB2     |           0|TRUE   | 39645.72| 39739.18| -19809.86|
|Hurdle Poisson |           0|TRUE   | 39643.72| 39729.99| -19809.86|


:::
:::


All fitted models had convergence code zero and a positive-definite Hessian.


::: {.cell}
::: {.cell-output-display}


Table: Numerical convergence checks for the fitted models.

|model                  |pdHess | convergence_code|
|:----------------------|:------|----------------:|
|beta_binomial_constant |TRUE   |                0|
|beta_binomial_scale    |TRUE   |                0|
|fledged_poisson        |TRUE   |                0|
|fledged_nbinom2        |TRUE   |                0|
|fledged_hurdle_poisson |TRUE   |                0|


:::
:::


The hurdle-Poisson reproduced the observed zero frequency: observed 23.65%, simulated median 23.65%, and 95% simulation interval 22.83-24.45%. This resolves the major zero-frequency failure of the ordinary NB2 model.

The positive-count component was not overdispersed. Its conditional Pearson dispersion was 0.538, compared with a median of 0.999 and a 95% simulation interval of 0.968-1.034 under the fitted zero-truncated Poisson. The observed value indicates underdispersion rather than overdispersion. Consistently, the alternative hurdle-NB2 estimated $\theta$ = 4.76e+06, effectively collapsing to the Poisson limit, and had an AIC higher by 2.00. Therefore, `truncated_nbinom2()` offers no improvement, and hurdle-Poisson remains the main realised-output model. The underdispersion means that its Poisson standard errors are conservative.

<details class="model-summary">
<summary>Show absolute-fledged coefficient table</summary>


::: {.cell}
::: {.cell-output-display}


Table: Coefficients from the positive-count and complete-failure components of the hurdle-Poisson model.

|component        |term                |    beta|     SE|  CI_low| CI_high|        z|      p|
|:----------------|:-------------------|-------:|------:|-------:|-------:|--------:|------:|
|positive_count   |(Intercept)         |  1.5195| 0.0167|  1.4867|  1.5522|  90.8460| 0.0000|
|positive_count   |rel_LD              | -0.0193| 0.0022| -0.0236| -0.0150|  -8.7667| 0.0000|
|positive_count   |age_classOLD        |  0.0289| 0.0126|  0.0043|  0.0536|   2.2985| 0.0215|
|positive_count   |temp_mean_c         | -0.0301| 0.0146| -0.0587| -0.0016|  -2.0692| 0.0385|
|positive_count   |year_c              | -0.0004| 0.0014| -0.0031|  0.0023|  -0.3042| 0.7610|
|positive_count   |rel_LD:age_classOLD |  0.0022| 0.0027| -0.0031|  0.0075|   0.8045| 0.4211|
|zero_probability |(Intercept)         | -1.2421| 0.0455| -1.3313| -1.1529| -27.2939| 0.0000|
|zero_probability |rel_LD              |  0.0767| 0.0048|  0.0673|  0.0862|  15.9116| 0.0000|
|zero_probability |temp_mean_c         |  0.3096| 0.0264|  0.2578|  0.3614|  11.7194| 0.0000|
|zero_probability |year_c              | -0.0035| 0.0026| -0.0086|  0.0017|  -1.3200| 0.1869|
|zero_probability |age_classOLD        | -0.0711| 0.0537| -0.1763|  0.0341|  -1.3240| 0.1855|


:::
:::


</details>

:::

### Temperature and realised fledgling number


::: {.cell}
::: {.cell-output-display}
![Marginal population-level prediction of absolute fledgling production from the hurdle-Poisson model, integrating complete-failure risk and positive fledgling number. Random effects are excluded; the ribbon is a 95% confidence interval.](figures/Fig5_5_fledged_count_temperature.png){width=1280}
:::
:::


Temperature increased the odds of complete brood failure ($\beta_{zero}$ = 0.310, 95% CI 0.258 to 0.361, $p$ < 0.001) and reduced the expected number fledged among positive broods ($\beta_{positive}$ = -0.030, 95% CI -0.059 to -0.002, $p$ = 0.039). The integrated population-level prediction declined by approximately 9.4% across a 1 &deg;C contrast centred on the mean temperature. Clutch size increased with temperature ($\beta$ = 0.096 eggs per 1 &deg;C), but this increase was insufficient to compensate for lower fledging success and increased complete-failure risk.

### Relative laying date and age effects


::: {.cell}
::: {.cell-output-display}
![Marginal population-level predictions of absolute fledgling production from the hurdle-Poisson model, integrating complete-failure risk and positive fledgling number. Random effects are excluded; ribbons are 95% confidence intervals.](figures/Fig5_6_fledged_count_rellD_age.png){width=1280}
:::
:::


Later relative laying date increased complete-failure risk ($\beta_{zero}$ = 0.0767, $p$ < 0.001) and reduced fledgling number among positive broods ($\beta_{positive}$ = -0.0193, $p$ < 0.001). Older females produced more fledglings in the positive-count component at the reference relative laying date ($\beta$ = 0.029, $p$ = 0.022). The `rel_LD` by age interaction was not supported in the positive-count component ($\beta$ = 0.002, $p$ = 0.421), and there was no supported long-term trend there ($\beta_{year}$ = -0.0004, $p$ = 0.761).

-->
</section>
</section>

<section id="figure-data-and-reproducibility" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="figure-data-and-reproducibility"><span class="header-section-number">5</span> Figure data and reproducibility</h2>
<p>Run <a href="R/09_prepare_reproductive_model_data.R"><code>R/09_prepare_reproductive_model_data.R</code></a>, then <a href="R/45_recentre_final_fledging_relLD.R"><code>R/45_recentre_final_fledging_relLD.R</code></a>, fit the models and outputs with <a href="R/30_fledging_chapter_models_figures.R"><code>R/30_fledging_chapter_models_figures.R</code></a>, refresh the paired figures with <a href="R/30c_refresh_phi_figures.R"><code>R/30c_refresh_phi_figures.R</code></a>, refresh the constant-<span class="math inline">\(\phi\)</span> diagnostic with <a href="R/49_refresh_phi_constant_simulation.R"><code>R/49_refresh_phi_constant_simulation.R</code></a>, run the conditional zero-frequency simulation with <a href="R/51_fledging_conditional_zero_simulation.R"><code>R/51_fledging_conditional_zero_simulation.R</code></a>, generate its diagnostic figure with <a href="R/52_plot_fledging_conditional_zero_diagnostic.R"><code>R/52_plot_fledging_conditional_zero_diagnostic.R</code></a>, and finally render this chapter.</p>
<ul>
<li><a href="tables/fig5_1_success_temperature.csv" download="fig5_1_success_temperature.csv">Figure 5.1 data</a></li>
<li><a href="tables/fig5_1b_phi_temperature.csv" download="fig5_1b_phi_temperature.csv">Figure 5.1 consistency data</a></li>
<li><a href="tables/fig5_2_success_rellD_age.csv" download="fig5_2_success_rellD_age.csv">Figure 5.2 data</a></li>
<li><a href="tables/fig5_3_phi_rellD.csv" download="fig5_3_phi_rellD.csv">Figure 5.3 data</a></li>
<li><a href="tables/fig5_3a_success_age.csv" download="fig5_3a_success_age.csv">Age and mean fledging-success data</a></li>
<li><a href="tables/fig5_3b_phi_age.csv" download="fig5_3b_phi_age.csv">Age and consistency data</a></li>
<li><a href="tables/fig5_4a_success_year.csv" download="fig5_4a_success_year.csv">Time and mean fledging-success data</a></li>
<li><a href="tables/fig5_4b_phi_year.csv" download="fig5_4b_phi_year.csv">Time and consistency data</a></li>
<li><a href="tables/fledging_precision_relLD_age_anova.csv" download="fledging_precision_relLD_age_anova.csv">Precision interaction model comparison</a></li>
<li><a href="tables/fledging_precision_relLD_age_interaction.csv" download="fledging_precision_relLD_age_interaction.csv">Precision interaction coefficient</a></li>
<li><a href="tables/fledging_zero_frequency_simulations.csv" download="fledging_zero_frequency_simulations.csv">Figure 5.4 simulation data</a></li>
<li><a href="tables/fledging_zero_frequency_conditional_simulations.csv" download="fledging_zero_frequency_conditional_simulations.csv">Conditional zero-frequency simulation data</a></li>
<li><a href="tables/fledging_bb_precision_comparison.csv" download="fledging_bb_precision_comparison.csv">Beta-binomial comparison</a></li>
<li><a href="tables/fledging_zero_frequency_summary.csv" download="fledging_zero_frequency_summary.csv">Zero-frequency diagnostic summary</a></li>
<li><a href="tables/fledging_zero_frequency_conditional_summary.csv" download="fledging_zero_frequency_conditional_summary.csv">Conditional zero-frequency diagnostic summary</a></li>
<li><a href="tables/fledging_phi_temperature_constant_simulation_summary.csv" download="fledging_phi_temperature_constant_simulation_summary.csv">Constant-phi simulation summary</a></li>
<li><a href="tables/fledging_phi_constant_simulations.csv" download="fledging_phi_constant_simulations.csv">Constant-phi simulation coefficients</a></li>
<li><a href="tables/figA_phi_constant_simulation.csv" download="figA_phi_constant_simulation.csv">Constant-phi histogram data</a></li>
<li><a href="tables/fledging_phi_temperature_conditional_survival.csv" download="fledging_phi_temperature_conditional_survival.csv">Temperature effect on phi conditional on brood survival</a></li>
</ul>
<p><a href="R/30_fledging_chapter_models_figures.R" download="30_fledging_chapter_models_figures.R">Download the complete chapter script</a>.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Fledging success"</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setlocale</span>(<span class="st">"LC_TIME"</span>, <span class="st">"C"</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>fmt <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">digits =</span> <span class="dv">3</span>) <span class="fu">formatC</span>(<span class="fu">as.numeric</span>(x), <span class="at">digits =</span> digits, <span class="at">format =</span> <span class="st">"f"</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>fmt_p <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">ifelse</span>(x <span class="sc">&lt;</span> <span class="fl">0.001</span>, <span class="st">"&lt; 0.001"</span>, <span class="fu">paste0</span>(<span class="st">"= "</span>, <span class="fu">fmt</span>(x, <span class="dv">3</span>)))</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>ci_low <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, se) beta <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>ci_high <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, se) beta <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data_derived/fledging_model_data.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>final_relLD_checks <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year_f) <span class="sc">|&gt;</span></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">annual_median =</span> <span class="fu">median</span>(rel_LD), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>max_abs_annual_median_relLD <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">abs</span>(final_relLD_checks<span class="sc">$</span>annual_median))</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>cor_relLD_temperature <span class="ot">&lt;-</span> <span class="fu">cor</span>(dat<span class="sc">$</span>rel_LD, dat<span class="sc">$</span>temp_mean_c)</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>source_fs <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data_derived/reproductive_model_data.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(fledged))</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>sample_tab <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_chapter_sample_summary.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>bb_compare <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_bb_precision_comparison.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>main_coef <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_bb_main_coefficients.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">CI_low =</span> <span class="fu">ci_low</span>(beta, SE), <span class="at">CI_high =</span> <span class="fu">ci_high</span>(beta, SE),</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">direction =</span> <span class="fu">case_when</span>(</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>      component <span class="sc">!=</span> <span class="st">"precision_log_phi"</span> <span class="sc">~</span> <span class="st">""</span>,</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>      beta <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"higher phi: lower conditional heterogeneity"</span>,</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>      beta <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"lower phi: higher conditional heterogeneity"</span>,</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"no directional change"</span></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>variance_decomp <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_variance_decomposition.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>temporal_success <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fig5_4a_success_year.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>temporal_phi <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fig5_4b_phi_year.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>age_trends <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_relLD_age_emtrends.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>zero_summary <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_zero_frequency_summary.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>zero_conditional <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tables/fledging_zero_frequency_conditional_summary.csv"</span>,</span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>count_zero <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledged_count_zero_frequency_summary.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>hurdle_compare <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledged_count_hurdle_optimizer_comparison.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>hurdle_coef <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledged_count_hurdle_coefficients.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CI_low =</span> <span class="fu">ci_low</span>(beta, SE), <span class="at">CI_high =</span> <span class="fu">ci_high</span>(beta, SE))</span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>hurdle_zero <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledged_count_hurdle_zero_frequency_summary.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a>positive_dispersion <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledged_hurdle_positive_dispersion_summary.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a>phi_mechanism <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_phi_temperature_constant_simulation_summary.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>phi_survival <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_phi_temperature_conditional_survival.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a>precision_age_cmp <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_precision_relLD_age_anova.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a>precision_age_int <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_precision_relLD_age_interaction.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a>phi_survival_temp <span class="ot">&lt;-</span> phi_survival <span class="sc">|&gt;</span></span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sample <span class="sc">==</span> <span class="st">"positive_broods_zero_truncated_joint"</span>,</span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a>         term <span class="sc">==</span> <span class="st">"precision:temp_mean_c"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>)</span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a>diagnostics <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_chapter_diagnostics.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a>clutch_coef <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/brms_cs_main_no_tempsd_coefficients.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a>count_temp_predictions <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fig5_5_fledged_count_temperature.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a>get_bb <span class="ot">&lt;-</span> <span class="cf">function</span>(component_name, term_name) {</span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a>  main_coef <span class="sc">|&gt;</span> <span class="fu">filter</span>(component <span class="sc">==</span> component_name, term <span class="sc">==</span> term_name) <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span>)</span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a>get_hurdle <span class="ot">&lt;-</span> <span class="cf">function</span>(component_name, term_name) {</span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a>  hurdle_coef <span class="sc">|&gt;</span> <span class="fu">filter</span>(component <span class="sc">==</span> component_name, term <span class="sc">==</span> term_name) <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span>)</span>
<span id="cb6-78"><a href="#cb6-78" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-79"><a href="#cb6-79" aria-hidden="true" tabindex="-1"></a>temp_center <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"tables/fledging_bb_centring_constants.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>temp_mean[<span class="dv">1</span>]</span>
<span id="cb6-80"><a href="#cb6-80" aria-hidden="true" tabindex="-1"></a>pred_low <span class="ot">&lt;-</span> count_temp_predictions <span class="sc">|&gt;</span></span>
<span id="cb6-81"><a href="#cb6-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_min</span>(<span class="fu">abs</span>(temp_mean <span class="sc">-</span> (temp_center <span class="sc">-</span> <span class="fl">0.5</span>)), <span class="at">n =</span> <span class="dv">1</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-82"><a href="#cb6-82" aria-hidden="true" tabindex="-1"></a>pred_high <span class="ot">&lt;-</span> count_temp_predictions <span class="sc">|&gt;</span></span>
<span id="cb6-83"><a href="#cb6-83" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_min</span>(<span class="fu">abs</span>(temp_mean <span class="sc">-</span> (temp_center <span class="sc">+</span> <span class="fl">0.5</span>)), <span class="at">n =</span> <span class="dv">1</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-84"><a href="#cb6-84" aria-hidden="true" tabindex="-1"></a>marginal_temp_percent <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">*</span> (pred_high<span class="sc">$</span>estimate <span class="sc">/</span> pred_low<span class="sc">$</span>estimate <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb6-85"><a href="#cb6-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-86"><a href="#cb6-86" aria-hidden="true" tabindex="-1"></a>source_1981_2019 <span class="ot">&lt;-</span> source_fs <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">between</span>(year, <span class="dv">1981</span>, <span class="dv">2019</span>))</span>
<span id="cb6-87"><a href="#cb6-87" aria-hidden="true" tabindex="-1"></a>source_known_age <span class="ot">&lt;-</span> source_1981_2019 <span class="sc">|&gt;</span> <span class="fu">filter</span>(age_class <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"YOUNG"</span>, <span class="st">"OLD"</span>))</span>
<span id="cb6-88"><a href="#cb6-88" aria-hidden="true" tabindex="-1"></a>sample_reconciliation <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-89"><a href="#cb6-89" aria-hidden="true" tabindex="-1"></a>  <span class="at">stage =</span> <span class="fu">c</span>(</span>
<span id="cb6-90"><a href="#cb6-90" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Validated fledging records, 1981-2019"</span>,</span>
<span id="cb6-91"><a href="#cb6-91" aria-hidden="true" tabindex="-1"></a>    <span class="st">"After restricting to 1981-2019"</span>,</span>
<span id="cb6-92"><a href="#cb6-92" aria-hidden="true" tabindex="-1"></a>    <span class="st">"After requiring the binary age class"</span>,</span>
<span id="cb6-93"><a href="#cb6-93" aria-hidden="true" tabindex="-1"></a>    <span class="st">"After requiring laying date for rel_LD"</span></span>
<span id="cb6-94"><a href="#cb6-94" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb6-95"><a href="#cb6-95" aria-hidden="true" tabindex="-1"></a>  <span class="at">broods =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(source_fs), <span class="fu">nrow</span>(source_1981_2019), <span class="fu">nrow</span>(source_known_age), <span class="fu">nrow</span>(dat)),</span>
<span id="cb6-96"><a href="#cb6-96" aria-hidden="true" tabindex="-1"></a>  <span class="at">zero_broods =</span> <span class="fu">c</span>(</span>
<span id="cb6-97"><a href="#cb6-97" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(source_fs<span class="sc">$</span>fledged <span class="sc">==</span> <span class="dv">0</span>), <span class="fu">sum</span>(source_1981_2019<span class="sc">$</span>fledged <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb6-98"><a href="#cb6-98" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(source_known_age<span class="sc">$</span>fledged <span class="sc">==</span> <span class="dv">0</span>), <span class="fu">sum</span>(dat<span class="sc">$</span>fledged <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb6-99"><a href="#cb6-99" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-100"><a href="#cb6-100" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-101"><a href="#cb6-101" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-102"><a href="#cb6-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-103"><a href="#cb6-103" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data</span></span>
<span id="cb6-104"><a href="#cb6-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-105"><a href="#cb6-105" aria-hidden="true" tabindex="-1"></a>The main response is **egg-to-fledging success, defined as the number of fledglings relative to the number of eggs laid**. Hereafter, *fledging success* is used as shorthand for this egg-to-fledging measure; the denominator is not the number of hatched nestlings.</span>
<span id="cb6-106"><a href="#cb6-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-107"><a href="#cb6-107" aria-hidden="true" tabindex="-1"></a>The model-ready data span <span class="in">`r sample_tab$years`</span> (<span class="in">`r sample_tab$seasons`</span> seasons) and contain <span class="in">`r format(sample_tab$broods, big.mark = ",")`</span> broods from <span class="in">`r format(sample_tab$females, big.mark = ",")`</span> females. Complete brood failure occurred in <span class="in">`r format(sample_tab$zero_broods, big.mark = ",")`</span> broods (<span class="in">`r fmt(sample_tab$zero_percent, 1)`</span>%). All zero-fledgling broods are retained. Records after 2019 are excluded because they have not yet been validated.</span>
<span id="cb6-108"><a href="#cb6-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-109"><a href="#cb6-109" aria-hidden="true" tabindex="-1"></a><span class="in">`rel_LD`</span> is laying date minus the annual median laying date, recalculated after all restrictions defining the final fledging-model sample. It describes a female's timing relative to other females breeding in the same season; it is not a measure of phenological mismatch. <span class="in">`temp_mean_c`</span> and <span class="in">`year_c`</span> retain the existing centring definitions.</span>
<span id="cb6-110"><a href="#cb6-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-111"><a href="#cb6-111" aria-hidden="true" tabindex="-1"></a>The predictors operate at different hierarchical levels. Relative laying date is centred within season and is therefore identified primarily by comparisons among broods breeding in the same year; the model contains <span class="in">`r format(sample_tab$broods, big.mark = ",")`</span> brood records, with repeated observations of females accounted for by the female random intercept. Spring temperature and year vary only among seasons, so inference for these predictors is based on variation across <span class="in">`r sample_tab$seasons`</span> breeding seasons. Consequently, annual predictors are estimated from substantially fewer independent temporal units than within-season predictors.</span>
<span id="cb6-112"><a href="#cb6-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-113"><a href="#cb6-113" aria-hidden="true" tabindex="-1"></a>Within-season centring separates variation in reproductive timing among females within a season from differences among seasons. In the final analytical sample, <span class="in">`rel_LD`</span> was recalculated as laying date minus the annual median laying date after all analytical filters; the maximum absolute annual median was <span class="in">`r format(max_abs_annual_median_relLD, scientific = TRUE, digits = 3)`</span> days (floating-point zero). The observed correlation with spring temperature was $r$ = <span class="in">`r fmt(cor_relLD_temperature, 4)`</span>.</span>
<span id="cb6-114"><a href="#cb6-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-115"><a href="#cb6-115" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Years <span class="pp">|</span> Seasons <span class="pp">|</span> Broods <span class="pp">|</span> Females <span class="pp">|</span> Broods with zero fledglings <span class="pp">|</span> Zero broods (%) <span class="pp">|</span></span>
<span id="cb6-116"><a href="#cb6-116" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---:|---:|</span></span>
<span id="cb6-117"><a href="#cb6-117" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`r sample_tab$years`</span> <span class="pp">|</span> <span class="in">`r sample_tab$seasons`</span> <span class="pp">|</span> <span class="in">`r format(sample_tab$broods, big.mark = ",")`</span> <span class="pp">|</span> <span class="in">`r format(sample_tab$females, big.mark = ",")`</span> <span class="pp">|</span> <span class="in">`r format(sample_tab$zero_broods, big.mark = ",")`</span> <span class="pp">|</span> <span class="in">`r fmt(sample_tab$zero_percent, 1)`</span> <span class="pp">|</span></span>
<span id="cb6-118"><a href="#cb6-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-121"><a href="#cb6-121" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-122"><a href="#cb6-122" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-123"><a href="#cb6-123" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb6-124"><a href="#cb6-124" aria-hidden="true" tabindex="-1"></a>  sample_reconciliation,</span>
<span id="cb6-125"><a href="#cb6-125" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Sample definition"</span>, <span class="st">"Broods"</span>, <span class="st">"Complete failures"</span>),</span>
<span id="cb6-126"><a href="#cb6-126" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Reconciliation of the validated fledging series with the model-ready sample."</span></span>
<span id="cb6-127"><a href="#cb6-127" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-128"><a href="#cb6-128" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-129"><a href="#cb6-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-130"><a href="#cb6-130" aria-hidden="true" tabindex="-1"></a><span class="fu">## Beta-binomial model structure</span></span>
<span id="cb6-131"><a href="#cb6-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-132"><a href="#cb6-132" aria-hidden="true" tabindex="-1"></a><span class="fu">### Constant versus predictor-dependent precision</span></span>
<span id="cb6-133"><a href="#cb6-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-134"><a href="#cb6-134" aria-hidden="true" tabindex="-1"></a>Two otherwise identical beta-binomial models were compared on the full dataset, including broods with zero fledglings. This comparison asks specifically whether allowing beta-binomial precision to vary with the prespecified predictors improves the model of fledging success.</span>
<span id="cb6-135"><a href="#cb6-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-138"><a href="#cb6-138" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-139"><a href="#cb6-139" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb6-140"><a href="#cb6-140" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb6-141"><a href="#cb6-141" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show model call"</span></span>
<span id="cb6-142"><a href="#cb6-142" aria-hidden="true" tabindex="-1"></a><span class="co">#| filename: "R/30_fledging_chapter_models_figures.R"</span></span>
<span id="cb6-143"><a href="#cb6-143" aria-hidden="true" tabindex="-1"></a>m_bb_constant <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(</span>
<span id="cb6-144"><a href="#cb6-144" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(fledged, clutch <span class="sc">-</span> fledged) <span class="sc">~</span></span>
<span id="cb6-145"><a href="#cb6-145" aria-hidden="true" tabindex="-1"></a>    rel_LD <span class="sc">*</span> age_class <span class="sc">+</span> temp_mean_c <span class="sc">+</span> year_c <span class="sc">+</span></span>
<span id="cb6-146"><a href="#cb6-146" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> year_f) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> female_id),</span>
<span id="cb6-147"><a href="#cb6-147" aria-hidden="true" tabindex="-1"></a>  <span class="at">dispformula =</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb6-148"><a href="#cb6-148" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">betabinomial</span>(), <span class="at">data =</span> dat</span>
<span id="cb6-149"><a href="#cb6-149" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-150"><a href="#cb6-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-151"><a href="#cb6-151" aria-hidden="true" tabindex="-1"></a>m_bb_scale <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(</span>
<span id="cb6-152"><a href="#cb6-152" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(fledged, clutch <span class="sc">-</span> fledged) <span class="sc">~</span></span>
<span id="cb6-153"><a href="#cb6-153" aria-hidden="true" tabindex="-1"></a>    rel_LD <span class="sc">*</span> age_class <span class="sc">+</span> temp_mean_c <span class="sc">+</span> year_c <span class="sc">+</span></span>
<span id="cb6-154"><a href="#cb6-154" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> year_f) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> female_id),</span>
<span id="cb6-155"><a href="#cb6-155" aria-hidden="true" tabindex="-1"></a>  <span class="at">dispformula =</span> <span class="sc">~</span> rel_LD <span class="sc">+</span> temp_mean_c <span class="sc">+</span> year_c <span class="sc">+</span> age_class,</span>
<span id="cb6-156"><a href="#cb6-156" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">betabinomial</span>(), <span class="at">data =</span> dat</span>
<span id="cb6-157"><a href="#cb6-157" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-158"><a href="#cb6-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-159"><a href="#cb6-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-162"><a href="#cb6-162" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-163"><a href="#cb6-163" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-164"><a href="#cb6-164" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb6-165"><a href="#cb6-165" aria-hidden="true" tabindex="-1"></a>  bb_compare <span class="sc">|&gt;</span> <span class="fu">select</span>(model, df, AIC, BIC, logLik, LR_chisq, LRT_df, LRT_p,</span>
<span id="cb6-166"><a href="#cb6-166" aria-hidden="true" tabindex="-1"></a>                       delta_AIC, delta_BIC),</span>
<span id="cb6-167"><a href="#cb6-167" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb6-168"><a href="#cb6-168" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Model"</span>, <span class="st">"df"</span>, <span class="st">"AIC"</span>, <span class="st">"BIC"</span>, <span class="st">"logLik"</span>, <span class="st">"LR chi-square"</span>,</span>
<span id="cb6-169"><a href="#cb6-169" aria-hidden="true" tabindex="-1"></a>                <span class="st">"df (LRT)"</span>, <span class="st">"p"</span>, <span class="st">"Delta AIC"</span>, <span class="st">"Delta BIC"</span>),</span>
<span id="cb6-170"><a href="#cb6-170" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Beta-binomial model comparison on the complete brood sample."</span></span>
<span id="cb6-171"><a href="#cb6-171" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-172"><a href="#cb6-172" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-173"><a href="#cb6-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-174"><a href="#cb6-174" aria-hidden="true" tabindex="-1"></a>The predictor-dependent precision model was clearly supported over the constant-precision model (likelihood-ratio $\chi^2_{<span class="in">`r bb_compare$LRT_df[2]`</span>}$ = <span class="in">`r fmt(bb_compare$LR_chisq[2], 2)`</span>, $p$ <span class="in">`r fmt_p(bb_compare$LRT_p[2])`</span>; $\Delta$AIC = <span class="in">`r fmt(bb_compare$delta_AIC[1], 1)`</span>, $\Delta$BIC = <span class="in">`r fmt(bb_compare$delta_BIC[1], 1)`</span>). It is therefore retained as the main model. This support comes from the beta-binomial response itself, not from a Gaussian model of positive fledgling counts.</span>
<span id="cb6-175"><a href="#cb6-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-176"><a href="#cb6-176" aria-hidden="true" tabindex="-1"></a><span class="fu">## Main beta-binomial location-scale model</span></span>
<span id="cb6-177"><a href="#cb6-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-178"><a href="#cb6-178" aria-hidden="true" tabindex="-1"></a>The location equation contains relative laying date, age class, their interaction, spring temperature, and time, with random intercepts for year and female. The precision equation contains relative laying date, spring temperature, time, and age class. Larger $\phi$ indicates lower conditional extra-binomial heterogeneity; smaller $\phi$ indicates higher conditional extra-binomial heterogeneity. This is conditional residual heterogeneity, not total phenotypic variance.</span>
<span id="cb6-179"><a href="#cb6-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-182"><a href="#cb6-182" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-183"><a href="#cb6-183" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb6-184"><a href="#cb6-184" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb6-185"><a href="#cb6-185" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Load saved model"</span></span>
<span id="cb6-186"><a href="#cb6-186" aria-hidden="true" tabindex="-1"></a>m_bb_scale <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"models/glmmTMB/fledging_bb_main_no_tempsd.rds"</span>)</span>
<span id="cb6-187"><a href="#cb6-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-188"><a href="#cb6-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-189"><a href="#cb6-189" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">details</span><span class="ot"> class</span><span class="op">=</span><span class="st">"model-summary"</span><span class="dt">&gt;</span></span>
<span id="cb6-190"><a href="#cb6-190" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">summary</span><span class="dt">&gt;</span>Show complete coefficient table<span class="dt">&lt;/</span><span class="kw">summary</span><span class="dt">&gt;</span></span>
<span id="cb6-191"><a href="#cb6-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-194"><a href="#cb6-194" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-195"><a href="#cb6-195" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb6-196"><a href="#cb6-196" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb6-197"><a href="#cb6-197" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_bb_scale)</span>
<span id="cb6-198"><a href="#cb6-198" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-199"><a href="#cb6-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-202"><a href="#cb6-202" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-203"><a href="#cb6-203" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb6-204"><a href="#cb6-204" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb6-205"><a href="#cb6-205" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb6-206"><a href="#cb6-206" aria-hidden="true" tabindex="-1"></a>  main_coef <span class="sc">|&gt;</span> <span class="fu">select</span>(component, term, beta, SE, CI_low, CI_high, z, p, direction),</span>
<span id="cb6-207"><a href="#cb6-207" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb6-208"><a href="#cb6-208" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Component"</span>, <span class="st">"Term"</span>, <span class="st">"Beta"</span>, <span class="st">"SE"</span>, <span class="st">"95% CI low"</span>, <span class="st">"95% CI high"</span>,</span>
<span id="cb6-209"><a href="#cb6-209" aria-hidden="true" tabindex="-1"></a>                <span class="st">"z"</span>, <span class="st">"p"</span>, <span class="st">"Direction"</span>),</span>
<span id="cb6-210"><a href="#cb6-210" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Location and precision coefficients from the main beta-binomial model."</span></span>
<span id="cb6-211"><a href="#cb6-211" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-212"><a href="#cb6-212" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-213"><a href="#cb6-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-214"><a href="#cb6-214" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;/</span><span class="kw">details</span><span class="dt">&gt;</span></span>
<span id="cb6-215"><a href="#cb6-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-216"><a href="#cb6-216" aria-hidden="true" tabindex="-1"></a>**Create coefficient tables and prediction data.** This step reads the saved model and creates the cached outputs used below.</span>
<span id="cb6-217"><a href="#cb6-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-220"><a href="#cb6-220" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-221"><a href="#cb6-221" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb6-222"><a href="#cb6-222" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb6-223"><a href="#cb6-223" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show output-generation step"</span></span>
<span id="cb6-224"><a href="#cb6-224" aria-hidden="true" tabindex="-1"></a><span class="co">#| filename: "R/30_fledging_chapter_models_figures.R"</span></span>
<span id="cb6-225"><a href="#cb6-225" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/30_fledging_chapter_models_figures.R"</span>)</span>
<span id="cb6-226"><a href="#cb6-226" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-227"><a href="#cb6-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-228"><a href="#cb6-228" aria-hidden="true" tabindex="-1"></a><span class="fu">## Between-year and between-female variation</span></span>
<span id="cb6-229"><a href="#cb6-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-232"><a href="#cb6-232" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-233"><a href="#cb6-233" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-234"><a href="#cb6-234" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb6-235"><a href="#cb6-235" aria-hidden="true" tabindex="-1"></a>  variance_decomp <span class="sc">|&gt;</span> <span class="fu">filter</span>(</span>
<span id="cb6-236"><a href="#cb6-236" aria-hidden="true" tabindex="-1"></a>    <span class="fu">grepl</span>(<span class="st">"random-intercept SD"</span>, quantity) <span class="sc">|</span></span>
<span id="cb6-237"><a href="#cb6-237" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"Reduction in year random-intercept variance"</span>, quantity)</span>
<span id="cb6-238"><a href="#cb6-238" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb6-239"><a href="#cb6-239" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Component"</span>, <span class="st">"Quantity"</span>, <span class="st">"Estimate"</span>, <span class="st">"Scale or unit"</span>),</span>
<span id="cb6-240"><a href="#cb6-240" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Random-effect standard deviations and nested-model reductions in year variance for fledging success."</span></span>
<span id="cb6-241"><a href="#cb6-241" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-242"><a href="#cb6-242" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-243"><a href="#cb6-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-244"><a href="#cb6-244" aria-hidden="true" tabindex="-1"></a>The year random-intercept SD was <span class="in">`r fmt(variance_decomp$estimate[variance_decomp$quantity == "Year random-intercept SD"], 3)`</span> and the female random-intercept SD was <span class="in">`r fmt(variance_decomp$estimate[variance_decomp$quantity == "Female random-intercept SD"], 3)`</span>, both on the logit scale. The two reduction estimates compare the year random-intercept variance with nested models that omit both seasonal predictors or retain temperature alone; they replace the previous, non-additive variance-of-the-linear-predictor shares. These quantities are not a decomposition of total phenotypic variance and are not directly comparable with $R^2$. The precision equation contains no random year or female effects, so no analogous random-effect SD is defined for $\phi$.</span>
<span id="cb6-245"><a href="#cb6-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-246"><a href="#cb6-246" aria-hidden="true" tabindex="-1"></a><span class="fu">### Fledging success and spring temperature</span></span>
<span id="cb6-247"><a href="#cb6-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-250"><a href="#cb6-250" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-251"><a href="#cb6-251" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-252"><a href="#cb6-252" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Population-level predictions against spring temperature from the beta-binomial model. Left: mean fledging success. Right: conditional consistency, expressed as phi. Random effects are excluded; ribbons are 95% confidence intervals and the x-axis covers the 5th-95th percentiles of observed temperature."</span></span>
<span id="cb6-253"><a href="#cb6-253" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figures/Fig5_1_success_phi_temperature.png"</span>)</span>
<span id="cb6-254"><a href="#cb6-254" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-255"><a href="#cb6-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-256"><a href="#cb6-256" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Show the plotting code in Figure code</span><span class="co">](figure_code.html#mean-and-consistency-against-temperature)</span>.</span>
<span id="cb6-257"><a href="#cb6-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-258"><a href="#cb6-258" aria-hidden="true" tabindex="-1"></a>Warmer springs were associated with lower mean fledging success ($\beta$ = <span class="in">`r fmt(get_bb("location", "temp_mean_c")$beta, 3)`</span>, 95% CI <span class="in">`r fmt(get_bb("location", "temp_mean_c")$CI_low, 3)`</span> to <span class="in">`r fmt(get_bb("location", "temp_mean_c")$CI_high, 3)`</span>, $p$ <span class="in">`r fmt_p(get_bb("location", "temp_mean_c")$p)`</span>) and higher precision ($\beta_{\log\phi}$ = <span class="in">`r fmt(get_bb("precision_log_phi", "temp_mean_c")$beta, 3)`</span>, $p$ <span class="in">`r fmt_p(get_bb("precision_log_phi", "temp_mean_c")$p)`</span>). Thus, both the location and scale effects of temperature were supported: fledging success was lower but conditionally more consistent in warmer springs.</span>
<span id="cb6-259"><a href="#cb6-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-260"><a href="#cb6-260" aria-hidden="true" tabindex="-1"></a><span class="fu">### Fledging success and relative laying date</span></span>
<span id="cb6-261"><a href="#cb6-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-264"><a href="#cb6-264" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-265"><a href="#cb6-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-266"><a href="#cb6-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Population-level predictions against relative laying date for young and old females from the beta-binomial location-scale model. Left: mean fledging success. Right: conditional consistency, expressed as phi. The precision equation contains additive effects of relative laying date and age but no interaction, so its age-specific curves have a common slope on the log-phi scale. Random effects are excluded; ribbons are 95% confidence intervals."</span></span>
<span id="cb6-267"><a href="#cb6-267" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figures/Fig5_2_success_rellD_age.png"</span>)</span>
<span id="cb6-268"><a href="#cb6-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-269"><a href="#cb6-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-270"><a href="#cb6-270" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Show the plotting code in Figure code</span><span class="co">](figure_code.html#fledging-success-figures)</span>.</span>
<span id="cb6-271"><a href="#cb6-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-272"><a href="#cb6-272" aria-hidden="true" tabindex="-1"></a>Relatively later females had lower fledging success. The relative-laying-date slope differed between age classes ($\beta_{\mathrm{LD\times OLD}}$ = <span class="in">`r fmt(get_bb("location", "rel_LD:age_classOLD")$beta, 3)`</span>, 95% CI <span class="in">`r fmt(get_bb("location", "rel_LD:age_classOLD")$CI_low, 3)`</span> to <span class="in">`r fmt(get_bb("location", "rel_LD:age_classOLD")$CI_high, 3)`</span>, $p$ <span class="in">`r fmt_p(get_bb("location", "rel_LD:age_classOLD")$p)`</span>). The <span class="in">`rel_LD`</span> main coefficient is conditional on the reference class, <span class="in">`age_class = YOUNG`</span>.</span>
<span id="cb6-273"><a href="#cb6-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-274"><a href="#cb6-274" aria-hidden="true" tabindex="-1"></a>Conditional slopes were calculated with <span class="in">`emmeans::emtrends()`</span> using the full variance-covariance matrix.</span>
<span id="cb6-275"><a href="#cb6-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-278"><a href="#cb6-278" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-279"><a href="#cb6-279" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-280"><a href="#cb6-280" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb6-281"><a href="#cb6-281" aria-hidden="true" tabindex="-1"></a>  age_trends, <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb6-282"><a href="#cb6-282" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Conditional relative-laying-date slopes by age class with 95% confidence intervals."</span></span>
<span id="cb6-283"><a href="#cb6-283" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-284"><a href="#cb6-284" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-285"><a href="#cb6-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-286"><a href="#cb6-286" aria-hidden="true" tabindex="-1"></a>Log-$\phi$ decreased with relative laying date ($\beta$ = <span class="in">`r fmt(get_bb("precision_log_phi", "rel_LD")$beta, 3)`</span>, 95% CI <span class="in">`r fmt(get_bb("precision_log_phi", "rel_LD")$CI_low, 3)`</span> to <span class="in">`r fmt(get_bb("precision_log_phi", "rel_LD")$CI_high, 3)`</span>, $p$ <span class="in">`r fmt_p(get_bb("precision_log_phi", "rel_LD")$p)`</span>). Thus, each one-day delay multiplied $\phi$ by <span class="in">`r fmt(exp(get_bb("precision_log_phi", "rel_LD")$beta), 3)`</span> (<span class="in">`r fmt(100 * (exp(get_bb("precision_log_phi", "rel_LD")$beta) - 1), 1)`</span>%), indicating greater conditional extra-binomial heterogeneity at later relative laying dates.</span>
<span id="cb6-287"><a href="#cb6-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-288"><a href="#cb6-288" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">details</span><span class="dt">&gt;</span></span>
<span id="cb6-289"><a href="#cb6-289" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">summary</span><span class="dt">&gt;&lt;</span><span class="kw">strong</span><span class="dt">&gt;</span>Check of the <span class="dt">&lt;</span><span class="kw">code</span><span class="dt">&gt;</span>rel_LD × age_class<span class="dt">&lt;/</span><span class="kw">code</span><span class="dt">&gt;</span> interaction in precision<span class="dt">&lt;/</span><span class="kw">strong</span><span class="dt">&gt;&lt;/</span><span class="kw">summary</span><span class="dt">&gt;</span></span>
<span id="cb6-290"><a href="#cb6-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-291"><a href="#cb6-291" aria-hidden="true" tabindex="-1"></a>Adding a <span class="in">`rel_LD × age_class`</span> interaction to the precision equation provided no clear evidence of age-specific slopes (likelihood-ratio $\chi^2_1$ = <span class="in">`r fmt(precision_age_cmp$chi_square[2], 2)`</span>, $p$ <span class="in">`r fmt_p(precision_age_cmp$p[2])`</span>); the models were essentially indistinguishable by AIC ($\Delta$AIC = <span class="in">`r fmt(abs(diff(precision_age_cmp$AIC)), 2)`</span>). The interaction coefficient was $\beta_{\log\phi}$ = <span class="in">`r fmt(precision_age_int$beta, 4)`</span> (95% CI <span class="in">`r fmt(precision_age_int$CI_low, 4)`</span> to <span class="in">`r fmt(precision_age_int$CI_high, 4)`</span>, $p$ <span class="in">`r fmt_p(precision_age_int$p)`</span>). We therefore retained the simpler additive precision model, in which the age-specific curves share a relative-laying-date slope on the log-$\phi$ scale.</span>
<span id="cb6-292"><a href="#cb6-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-293"><a href="#cb6-293" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;/</span><span class="kw">details</span><span class="dt">&gt;</span></span>
<span id="cb6-294"><a href="#cb6-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-295"><a href="#cb6-295" aria-hidden="true" tabindex="-1"></a><span class="fu">### Fledging success and female age</span></span>
<span id="cb6-296"><a href="#cb6-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-297"><a href="#cb6-297" aria-hidden="true" tabindex="-1"></a>Older females had higher mean fledging success at the reference relative laying date ($\beta$ = <span class="in">`r fmt(get_bb("location", "age_classOLD")$beta, 3)`</span>, $p$ <span class="in">`r fmt_p(get_bb("location", "age_classOLD")$p)`</span>) and higher precision ($\beta_{\log\phi}$ = <span class="in">`r fmt(get_bb("precision_log_phi", "age_classOLD")$beta, 3)`</span>, $p$ <span class="in">`r fmt_p(get_bb("precision_log_phi", "age_classOLD")$p)`</span>). Thus, both the location and scale age effects were supported; the location coefficient is conditional on <span class="in">`rel_LD = 0`</span> because the location equation contains <span class="in">`rel_LD × age_class`</span>.</span>
<span id="cb6-298"><a href="#cb6-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-301"><a href="#cb6-301" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-302"><a href="#cb6-302" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-303"><a href="#cb6-303" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Model-estimated mean fledging success (left) and beta-binomial consistency (right) for young and old females at the reference relative laying date, mean spring temperature, and mean study year. Points are population-level predictions; error bars are 95% confidence intervals and random effects are excluded."</span></span>
<span id="cb6-304"><a href="#cb6-304" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figures/Fig5_3b_phi_age.png"</span>)</span>
<span id="cb6-305"><a href="#cb6-305" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-306"><a href="#cb6-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-307"><a href="#cb6-307" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Show the plotting code in Figure code</span><span class="co">](figure_code.html#mean-and-consistency-by-female-age)</span>.</span>
<span id="cb6-308"><a href="#cb6-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-309"><a href="#cb6-309" aria-hidden="true" tabindex="-1"></a><span class="fu">### Changes over time</span></span>
<span id="cb6-310"><a href="#cb6-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-313"><a href="#cb6-313" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-314"><a href="#cb6-314" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-315"><a href="#cb6-315" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Temporal predictions from the beta-binomial location-scale model after accounting for spring temperature. Left: population-level conditional prediction for mean fledging success. Right: conditional consistency, expressed as phi; higher values indicate greater consistency. Spring temperature is held at its study-wide mean, random effects are excluded, and ribbons show 95% confidence intervals."</span></span>
<span id="cb6-316"><a href="#cb6-316" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figures/Fig5_4_time_location_scale.png"</span>)</span>
<span id="cb6-317"><a href="#cb6-317" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-318"><a href="#cb6-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-319"><a href="#cb6-319" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Show the plotting code in Figure code</span><span class="co">](figure_code.html#conditional-temporal-trajectories)</span>.</span>
<span id="cb6-320"><a href="#cb6-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-321"><a href="#cb6-321" aria-hidden="true" tabindex="-1"></a>After accounting for spring temperature, there was no clear evidence of temporal change in mean egg-to-fledging success ($\beta$ = <span class="in">`r fmt(get_bb("location", "year_c")$beta, 4)`</span>, 95% CI <span class="in">`r fmt(get_bb("location", "year_c")$CI_low, 4)`</span> to <span class="in">`r fmt(get_bb("location", "year_c")$CI_high, 4)`</span>, $p$ <span class="in">`r fmt_p(get_bb("location", "year_c")$p)`</span>). Reproductive consistency likewise showed no clear temporal trend ($\beta_{\log\phi}$ = <span class="in">`r fmt(get_bb("precision_log_phi", "year_c")$beta, 4)`</span>, 95% CI <span class="in">`r fmt(get_bb("precision_log_phi", "year_c")$CI_low, 4)`</span> to <span class="in">`r fmt(get_bb("precision_log_phi", "year_c")$CI_high, 4)`</span>, $p$ <span class="in">`r fmt_p(get_bb("precision_log_phi", "year_c")$p)`</span>).</span>
<span id="cb6-322"><a href="#cb6-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-323"><a href="#cb6-323" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">details</span><span class="dt">&gt;</span></span>
<span id="cb6-324"><a href="#cb6-324" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">summary</span><span class="dt">&gt;&lt;</span><span class="kw">strong</span><span class="dt">&gt;</span>Appendix: checks of the temperature effect on precision<span class="dt">&lt;/</span><span class="kw">strong</span><span class="dt">&gt;&lt;/</span><span class="kw">summary</span><span class="dt">&gt;</span></span>
<span id="cb6-325"><a href="#cb6-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-326"><a href="#cb6-326" aria-hidden="true" tabindex="-1"></a>The temperature effect on $\phi$ was not explained by the changing mean or the response ceiling (constant-$\phi$ simulation: exceeded in <span class="in">`r fmt(100 * phi_mechanism$proportion_at_least_observed, 1)`</span>% of replicates), and it remained positive after conditioning on broods with at least one fledgling in a zero-truncated beta-binomial model ($\beta_{\log\phi}$ = <span class="in">`r fmt(phi_survival_temp$beta, 3)`</span>, 95% CI <span class="in">`r fmt(phi_survival_temp$CI_low, 3)`</span> to <span class="in">`r fmt(phi_survival_temp$CI_high, 3)`</span>, $p$ <span class="in">`r fmt_p(phi_survival_temp$p)`</span>).</span>
<span id="cb6-327"><a href="#cb6-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-328"><a href="#cb6-328" aria-hidden="true" tabindex="-1"></a>To assess whether the temperature effect on $\phi$ could arise mechanically because mean success moved away from the upper boundary, 200 datasets were simulated with the fitted conditional means held fixed but with constant $\phi$. The median simulated temperature coefficient in an auxiliary precision model was <span class="in">`r fmt(phi_mechanism$simulated_median, 4)`</span> (95% simulation interval <span class="in">`r fmt(phi_mechanism$simulation_CI_low, 4)`</span> to <span class="in">`r fmt(phi_mechanism$simulation_CI_high, 4)`</span>). The corresponding observed auxiliary coefficient was <span class="in">`r fmt(phi_mechanism$observed_auxiliary_beta, 4)`</span>; only <span class="in">`r fmt(100 * phi_mechanism$proportion_at_least_observed, 1)`</span>% of simulations were at least this large. All <span class="in">`r phi_mechanism$simulations`</span> optimisations converged without reaching parameter boundaries. This targeted check does not distinguish biological from other unmodelled sources of conditional heterogeneity.</span>
<span id="cb6-329"><a href="#cb6-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-332"><a href="#cb6-332" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-333"><a href="#cb6-333" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-334"><a href="#cb6-334" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Temperature coefficients from 200 datasets simulated with constant phi. The orange line is the observed auxiliary coefficient. This is a diagnostic figure, not a biological effect estimate."</span></span>
<span id="cb6-335"><a href="#cb6-335" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figures/FigA_phi_constant_simulation.png"</span>)</span>
<span id="cb6-336"><a href="#cb6-336" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-337"><a href="#cb6-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-338"><a href="#cb6-338" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Show the plotting code in Figure code</span><span class="co">](figure_code.html#constant-phi-simulation-diagnostic)</span>.</span>
<span id="cb6-339"><a href="#cb6-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-340"><a href="#cb6-340" aria-hidden="true" tabindex="-1"></a>To determine whether higher $\phi$ in warmer springs was instead produced by the increased probability of complete brood failure, a correctly zero-truncated beta-binomial likelihood was fitted to the <span class="in">`r sum(dat$fledged &gt; 0)`</span> broods with at least one fledgling. The location and precision equations were jointly re-estimated, while the fitted year and female contributions were retained as offsets. The temperature coefficient in precision remained positive ($\beta_{\log\phi}$ = <span class="in">`r fmt(phi_survival_temp$beta, 4)`</span>, 95% CI <span class="in">`r fmt(phi_survival_temp$CI_low, 4)`</span> to <span class="in">`r fmt(phi_survival_temp$CI_high, 4)`</span>, $p$ <span class="in">`r fmt_p(phi_survival_temp$p)`</span>). The optimisation converged without a boundary estimate. Thus, the association is not attributable solely to warmer springs producing more complete failures and leaving a more homogeneous surviving subset. It may be discussed as higher conditional residual consistency among non-failed broods, but not as evidence of a causal temperature effect or a change in total phenotypic variance.</span>
<span id="cb6-341"><a href="#cb6-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-342"><a href="#cb6-342" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;/</span><span class="kw">details</span><span class="dt">&gt;</span></span>
<span id="cb6-343"><a href="#cb6-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-344"><a href="#cb6-344" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">details</span><span class="dt">&gt;</span></span>
<span id="cb6-345"><a href="#cb6-345" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">summary</span><span class="dt">&gt;&lt;</span><span class="kw">strong</span><span class="dt">&gt;</span>Model adequacy for complete brood failures<span class="dt">&lt;/</span><span class="kw">strong</span><span class="dt">&gt;&lt;/</span><span class="kw">summary</span><span class="dt">&gt;</span></span>
<span id="cb6-346"><a href="#cb6-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-347"><a href="#cb6-347" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Simulation-based zero-frequency check</span></span>
<span id="cb6-348"><a href="#cb6-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-349"><a href="#cb6-349" aria-hidden="true" tabindex="-1"></a>Two simulation checks address different questions. First, 1,000 datasets were simulated with the fitted year and female random effects held fixed, directly assessing calibration for the observed groups. Second, <span class="in">`simulate.glmmTMB()`</span> was used to generate new random-effect realisations from their estimated distributions, assessing unconditional calibration for hypothetical new groups. The current <span class="in">`glmmTMB`</span> implementation cannot condition <span class="in">`simulate()`</span> on the fitted random effects, so the conditional check was generated directly from the fitted beta-binomial means and precision values.</span>
<span id="cb6-350"><a href="#cb6-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-353"><a href="#cb6-353" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-354"><a href="#cb6-354" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-355"><a href="#cb6-355" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distribution of the proportion of complete brood failures in 1,000 datasets simulated conditionally on the fitted year and female random effects. The orange vertical line is the observed proportion."</span></span>
<span id="cb6-356"><a href="#cb6-356" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figures/Fig5_4_zero_frequency_diagnostic.png"</span>)</span>
<span id="cb6-357"><a href="#cb6-357" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-358"><a href="#cb6-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-359"><a href="#cb6-359" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Show the plotting code in Figure code</span><span class="co">](figure_code.html#fledging-success-figures)</span>.</span>
<span id="cb6-360"><a href="#cb6-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-361"><a href="#cb6-361" aria-hidden="true" tabindex="-1"></a>The observed frequency was <span class="in">`r fmt(100 * zero_conditional$observed, 1)`</span>%. Conditional simulations had a median of <span class="in">`r fmt(100 * zero_conditional$simulated_median, 1)`</span>% (95% simulation interval <span class="in">`r fmt(100 * zero_conditional$simulation_CI_low, 1)`</span>–<span class="in">`r fmt(100 * zero_conditional$simulation_CI_high, 1)`</span>%), whereas unconditional <span class="in">`simulate.glmmTMB()`</span> simulations had a median of <span class="in">`r fmt(100 * zero_summary$simulated_median, 1)`</span>% (95% simulation interval <span class="in">`r fmt(100 * zero_summary$simulation_CI_low, 1)`</span>–<span class="in">`r fmt(100 * zero_summary$simulation_CI_high, 1)`</span>%). Thus, the conditional check underpredicted zeros while the unconditional check overpredicted them. The fitted model does not reproduce the observed zero frequency exactly, but the direction of the discrepancy depends on whether inference is conditional on the observed groups or averaged over new random-effect realisations. This is a model-adequacy diagnostic, not a separate biological hypothesis test, and does not by itself justify an additional zero-inflation component.</span>
<span id="cb6-362"><a href="#cb6-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-363"><a href="#cb6-363" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;/</span><span class="kw">details</span><span class="dt">&gt;</span></span>
<span id="cb6-364"><a href="#cb6-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-365"><a href="#cb6-365" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- The realised fledgling production analysis is now maintained in</span></span>
<span id="cb6-366"><a href="#cb6-366" aria-hidden="true" tabindex="-1"></a><span class="co">realised_fledgling_production.qmd. The archived source below is excluded</span></span>
<span id="cb6-367"><a href="#cb6-367" aria-hidden="true" tabindex="-1"></a><span class="co">from this chapter's rendered output.</span></span>
<span id="cb6-368"><a href="#cb6-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-369"><a href="#cb6-369" aria-hidden="true" tabindex="-1"></a><span class="co">## Realised fledgling production</span></span>
<span id="cb6-370"><a href="#cb6-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-371"><a href="#cb6-371" aria-hidden="true" tabindex="-1"></a><span class="co">Absolute fledgling production is the number of fledglings produced per brood. It is analysed separately from fledging success and does not include clutch size as a covariate, because clutch size is a responsive reproductive trait and may mediate the total effect of temperature and timing.</span></span>
<span id="cb6-372"><a href="#cb6-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-373"><a href="#cb6-373" aria-hidden="true" tabindex="-1"></a><span class="co">This analysis does not contain a scale equation. Neither the Bernoulli complete-failure component nor the zero-truncated Poisson positive-count component has a freely estimated dispersion parameter. Consequently, the hurdle model addresses realised output and failure risk, not reproductive consistency; consistency is evaluated in the Gaussian clutch-size and beta-binomial fledging-success models.</span></span>
<span id="cb6-374"><a href="#cb6-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-375"><a href="#cb6-375" aria-hidden="true" tabindex="-1"></a><span class="al">###</span><span class="co"> Model specification</span></span>
<span id="cb6-376"><a href="#cb6-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-379"><a href="#cb6-379" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-380"><a href="#cb6-380" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb6-381"><a href="#cb6-381" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: show</span></span>
<span id="cb6-382"><a href="#cb6-382" aria-hidden="true" tabindex="-1"></a><span class="co">#| filename: "R/30_fledging_chapter_models_figures.R"</span></span>
<span id="cb6-383"><a href="#cb6-383" aria-hidden="true" tabindex="-1"></a><span class="co">m_count_hurdle &lt;- glmmTMB(</span></span>
<span id="cb6-384"><a href="#cb6-384" aria-hidden="true" tabindex="-1"></a><span class="co">  fledged ~ rel_LD * age_class + temp_mean_c + year_c +</span></span>
<span id="cb6-385"><a href="#cb6-385" aria-hidden="true" tabindex="-1"></a><span class="co">    (1 | year_f) + (1 | female_id),</span></span>
<span id="cb6-386"><a href="#cb6-386" aria-hidden="true" tabindex="-1"></a><span class="co">  ziformula = ~ rel_LD + temp_mean_c + year_c + age_class,</span></span>
<span id="cb6-387"><a href="#cb6-387" aria-hidden="true" tabindex="-1"></a><span class="co">  family = truncated_poisson(), data = dat</span></span>
<span id="cb6-388"><a href="#cb6-388" aria-hidden="true" tabindex="-1"></a><span class="co">)</span></span>
<span id="cb6-389"><a href="#cb6-389" aria-hidden="true" tabindex="-1"></a><span class="co">```</span></span>
<span id="cb6-390"><a href="#cb6-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-391"><a href="#cb6-391" aria-hidden="true" tabindex="-1"></a><span class="co">The ordinary NB2 model is retained only as a sensitivity check because it reproduced `r fmt(100 * count_zero$simulated_median, 1)`% zero broods versus `r fmt(100 * count_zero$observed, 1)`% observed; the hurdle-Poisson is the final model of realised fledgling production.</span></span>
<span id="cb6-392"><a href="#cb6-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-393"><a href="#cb6-393" aria-hidden="true" tabindex="-1"></a><span class="co">::: {.callout-note collapse="true"}</span></span>
<span id="cb6-394"><a href="#cb6-394" aria-hidden="true" tabindex="-1"></a><span class="al">###</span><span class="co"> Model diagnostics</span></span>
<span id="cb6-395"><a href="#cb6-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-396"><a href="#cb6-396" aria-hidden="true" tabindex="-1"></a><span class="co">A hurdle model was fitted to separate the probability of complete failure from the positive fledgling-count distribution. After alternative optimisation, both hurdle-NB2 and hurdle-Poisson converged with positive-definite Hessians. Their log-likelihoods were effectively identical, and the simpler hurdle-Poisson had lower AIC and BIC.</span></span>
<span id="cb6-397"><a href="#cb6-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-400"><a href="#cb6-400" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-401"><a href="#cb6-401" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-402"><a href="#cb6-402" aria-hidden="true" tabindex="-1"></a><span class="co">kable(</span></span>
<span id="cb6-403"><a href="#cb6-403" aria-hidden="true" tabindex="-1"></a><span class="co">  hurdle_compare, digits = 3,</span></span>
<span id="cb6-404"><a href="#cb6-404" aria-hidden="true" tabindex="-1"></a><span class="co">  col.names = c("Model", "Convergence", "pdHess", "AIC", "BIC", "logLik"),</span></span>
<span id="cb6-405"><a href="#cb6-405" aria-hidden="true" tabindex="-1"></a><span class="co">  caption = "Comparison of the two fitted hurdle count distributions."</span></span>
<span id="cb6-406"><a href="#cb6-406" aria-hidden="true" tabindex="-1"></a><span class="co">)</span></span>
<span id="cb6-407"><a href="#cb6-407" aria-hidden="true" tabindex="-1"></a><span class="co">```</span></span>
<span id="cb6-408"><a href="#cb6-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-409"><a href="#cb6-409" aria-hidden="true" tabindex="-1"></a><span class="co">All fitted models had convergence code zero and a positive-definite Hessian.</span></span>
<span id="cb6-410"><a href="#cb6-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-413"><a href="#cb6-413" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-414"><a href="#cb6-414" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-415"><a href="#cb6-415" aria-hidden="true" tabindex="-1"></a><span class="co">kable(diagnostics, caption = "Numerical convergence checks for the fitted models.")</span></span>
<span id="cb6-416"><a href="#cb6-416" aria-hidden="true" tabindex="-1"></a><span class="co">```</span></span>
<span id="cb6-417"><a href="#cb6-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-418"><a href="#cb6-418" aria-hidden="true" tabindex="-1"></a><span class="co">The hurdle-Poisson reproduced the observed zero frequency: observed `r fmt(100 * hurdle_zero$observed, 2)`%, simulated median `r fmt(100 * hurdle_zero$simulated_median, 2)`%, and 95% simulation interval `r fmt(100 * hurdle_zero$simulation_CI_low, 2)`-`r fmt(100 * hurdle_zero$simulation_CI_high, 2)`%. This resolves the major zero-frequency failure of the ordinary NB2 model.</span></span>
<span id="cb6-419"><a href="#cb6-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-420"><a href="#cb6-420" aria-hidden="true" tabindex="-1"></a><span class="co">The positive-count component was not overdispersed. Its conditional Pearson dispersion was `r fmt(positive_dispersion$observed_Pearson_dispersion, 3)`, compared with a median of `r fmt(positive_dispersion$simulated_median, 3)` and a 95% simulation interval of `r fmt(positive_dispersion$simulation_CI_low, 3)`-`r fmt(positive_dispersion$simulation_CI_high, 3)` under the fitted zero-truncated Poisson. The observed value indicates underdispersion rather than overdispersion. Consistently, the alternative hurdle-NB2 estimated $\theta$ = `r format(positive_dispersion$hurdle_nbinom2_theta, scientific = TRUE, digits = 3)`, effectively collapsing to the Poisson limit, and had an AIC higher by `r fmt(positive_dispersion$delta_AIC_nbinom2, 2)`. Therefore, `truncated_nbinom2()` offers no improvement, and hurdle-Poisson remains the main realised-output model. The underdispersion means that its Poisson standard errors are conservative.</span></span>
<span id="cb6-421"><a href="#cb6-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-422"><a href="#cb6-422" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;details class="model-summary"&gt;</span></span>
<span id="cb6-423"><a href="#cb6-423" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;summary&gt;Show absolute-fledged coefficient table&lt;/summary&gt;</span></span>
<span id="cb6-424"><a href="#cb6-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-427"><a href="#cb6-427" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-428"><a href="#cb6-428" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-429"><a href="#cb6-429" aria-hidden="true" tabindex="-1"></a><span class="co">kable(</span></span>
<span id="cb6-430"><a href="#cb6-430" aria-hidden="true" tabindex="-1"></a><span class="co">  hurdle_coef |&gt; select(component, term, beta, SE, CI_low, CI_high, z, p), digits = 4,</span></span>
<span id="cb6-431"><a href="#cb6-431" aria-hidden="true" tabindex="-1"></a><span class="co">  caption = "Coefficients from the positive-count and complete-failure components of the hurdle-Poisson model."</span></span>
<span id="cb6-432"><a href="#cb6-432" aria-hidden="true" tabindex="-1"></a><span class="co">)</span></span>
<span id="cb6-433"><a href="#cb6-433" aria-hidden="true" tabindex="-1"></a><span class="co">```</span></span>
<span id="cb6-434"><a href="#cb6-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-435"><a href="#cb6-435" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;/details&gt;</span></span>
<span id="cb6-436"><a href="#cb6-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-437"><a href="#cb6-437" aria-hidden="true" tabindex="-1"></a><span class="co">:::</span></span>
<span id="cb6-438"><a href="#cb6-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-439"><a href="#cb6-439" aria-hidden="true" tabindex="-1"></a><span class="al">###</span><span class="co"> Temperature and realised fledgling number</span></span>
<span id="cb6-440"><a href="#cb6-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-443"><a href="#cb6-443" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-444"><a href="#cb6-444" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-445"><a href="#cb6-445" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Marginal population-level prediction of absolute fledgling production from the hurdle-Poisson model, integrating complete-failure risk and positive fledgling number. Random effects are excluded; the ribbon is a 95% confidence interval."</span></span>
<span id="cb6-446"><a href="#cb6-446" aria-hidden="true" tabindex="-1"></a><span class="co">knitr::include_graphics("figures/Fig5_5_fledged_count_temperature.png")</span></span>
<span id="cb6-447"><a href="#cb6-447" aria-hidden="true" tabindex="-1"></a><span class="co">```</span></span>
<span id="cb6-448"><a href="#cb6-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-449"><a href="#cb6-449" aria-hidden="true" tabindex="-1"></a><span class="co">Temperature increased the odds of complete brood failure ($\beta_{zero}$ = `r fmt(get_hurdle("zero_probability", "temp_mean_c")$beta, 3)`, 95% CI `r fmt(get_hurdle("zero_probability", "temp_mean_c")$CI_low, 3)` to `r fmt(get_hurdle("zero_probability", "temp_mean_c")$CI_high, 3)`, $p$ `r fmt_p(get_hurdle("zero_probability", "temp_mean_c")$p)`) and reduced the expected number fledged among positive broods ($\beta_{positive}$ = `r fmt(get_hurdle("positive_count", "temp_mean_c")$beta, 3)`, 95% CI `r fmt(get_hurdle("positive_count", "temp_mean_c")$CI_low, 3)` to `r fmt(get_hurdle("positive_count", "temp_mean_c")$CI_high, 3)`, $p$ `r fmt_p(get_hurdle("positive_count", "temp_mean_c")$p)`). The integrated population-level prediction declined by approximately `r fmt(abs(marginal_temp_percent), 1)`% across a 1 &amp;deg;C contrast centred on the mean temperature. Clutch size increased with temperature ($\beta$ = `r fmt(clutch_coef$median[clutch_coef$component == "location" &amp; clutch_coef$term == "temp_mean_c"], 3)` eggs per 1 &amp;deg;C), but this increase was insufficient to compensate for lower fledging success and increased complete-failure risk.</span></span>
<span id="cb6-450"><a href="#cb6-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-451"><a href="#cb6-451" aria-hidden="true" tabindex="-1"></a><span class="al">###</span><span class="co"> Relative laying date and age effects</span></span>
<span id="cb6-452"><a href="#cb6-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-455"><a href="#cb6-455" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-456"><a href="#cb6-456" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-457"><a href="#cb6-457" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Marginal population-level predictions of absolute fledgling production from the hurdle-Poisson model, integrating complete-failure risk and positive fledgling number. Random effects are excluded; ribbons are 95% confidence intervals."</span></span>
<span id="cb6-458"><a href="#cb6-458" aria-hidden="true" tabindex="-1"></a><span class="co">knitr::include_graphics("figures/Fig5_6_fledged_count_rellD_age.png")</span></span>
<span id="cb6-459"><a href="#cb6-459" aria-hidden="true" tabindex="-1"></a><span class="co">```</span></span>
<span id="cb6-460"><a href="#cb6-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-461"><a href="#cb6-461" aria-hidden="true" tabindex="-1"></a><span class="co">Later relative laying date increased complete-failure risk ($\beta_{zero}$ = `r fmt(get_hurdle("zero_probability", "rel_LD")$beta, 4)`, $p$ `r fmt_p(get_hurdle("zero_probability", "rel_LD")$p)`) and reduced fledgling number among positive broods ($\beta_{positive}$ = `r fmt(get_hurdle("positive_count", "rel_LD")$beta, 4)`, $p$ `r fmt_p(get_hurdle("positive_count", "rel_LD")$p)`). Older females produced more fledglings in the positive-count component at the reference relative laying date ($\beta$ = `r fmt(get_hurdle("positive_count", "age_classOLD")$beta, 3)`, $p$ `r fmt_p(get_hurdle("positive_count", "age_classOLD")$p)`). The `rel_LD` by age interaction was not supported in the positive-count component ($\beta$ = `r fmt(get_hurdle("positive_count", "rel_LD:age_classOLD")$beta, 3)`, $p$ `r fmt_p(get_hurdle("positive_count", "rel_LD:age_classOLD")$p)`), and there was no supported long-term trend there ($\beta_{year}$ = `r fmt(get_hurdle("positive_count", "year_c")$beta, 4)`, $p$ `r fmt_p(get_hurdle("positive_count", "year_c")$p)`).</span></span>
<span id="cb6-462"><a href="#cb6-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-463"><a href="#cb6-463" aria-hidden="true" tabindex="-1"></a><span class="co">--&gt;</span></span>
<span id="cb6-464"><a href="#cb6-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-465"><a href="#cb6-465" aria-hidden="true" tabindex="-1"></a><span class="fu">## Figure data and reproducibility</span></span>
<span id="cb6-466"><a href="#cb6-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-467"><a href="#cb6-467" aria-hidden="true" tabindex="-1"></a>Run <span class="co">[</span><span class="ot">`R/09_prepare_reproductive_model_data.R`</span><span class="co">](R/09_prepare_reproductive_model_data.R)</span>, then <span class="co">[</span><span class="ot">`R/45_recentre_final_fledging_relLD.R`</span><span class="co">](R/45_recentre_final_fledging_relLD.R)</span>, fit the models and outputs with <span class="co">[</span><span class="ot">`R/30_fledging_chapter_models_figures.R`</span><span class="co">](R/30_fledging_chapter_models_figures.R)</span>, refresh the paired figures with <span class="co">[</span><span class="ot">`R/30c_refresh_phi_figures.R`</span><span class="co">](R/30c_refresh_phi_figures.R)</span>, refresh the constant-$\phi$ diagnostic with <span class="co">[</span><span class="ot">`R/49_refresh_phi_constant_simulation.R`</span><span class="co">](R/49_refresh_phi_constant_simulation.R)</span>, run the conditional zero-frequency simulation with <span class="co">[</span><span class="ot">`R/51_fledging_conditional_zero_simulation.R`</span><span class="co">](R/51_fledging_conditional_zero_simulation.R)</span>, generate its diagnostic figure with <span class="co">[</span><span class="ot">`R/52_plot_fledging_conditional_zero_diagnostic.R`</span><span class="co">](R/52_plot_fledging_conditional_zero_diagnostic.R)</span>, and finally render this chapter.</span>
<span id="cb6-468"><a href="#cb6-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-469"><a href="#cb6-469" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Figure 5.1 data</span><span class="co">](tables/fig5_1_success_temperature.csv)</span>{download="fig5_1_success_temperature.csv"}</span>
<span id="cb6-470"><a href="#cb6-470" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Figure 5.1 consistency data</span><span class="co">](tables/fig5_1b_phi_temperature.csv)</span>{download="fig5_1b_phi_temperature.csv"}</span>
<span id="cb6-471"><a href="#cb6-471" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Figure 5.2 data</span><span class="co">](tables/fig5_2_success_rellD_age.csv)</span>{download="fig5_2_success_rellD_age.csv"}</span>
<span id="cb6-472"><a href="#cb6-472" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Figure 5.3 data</span><span class="co">](tables/fig5_3_phi_rellD.csv)</span>{download="fig5_3_phi_rellD.csv"}</span>
<span id="cb6-473"><a href="#cb6-473" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Age and mean fledging-success data</span><span class="co">](tables/fig5_3a_success_age.csv)</span>{download="fig5_3a_success_age.csv"}</span>
<span id="cb6-474"><a href="#cb6-474" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Age and consistency data</span><span class="co">](tables/fig5_3b_phi_age.csv)</span>{download="fig5_3b_phi_age.csv"}</span>
<span id="cb6-475"><a href="#cb6-475" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Time and mean fledging-success data</span><span class="co">](tables/fig5_4a_success_year.csv)</span>{download="fig5_4a_success_year.csv"}</span>
<span id="cb6-476"><a href="#cb6-476" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Time and consistency data</span><span class="co">](tables/fig5_4b_phi_year.csv)</span>{download="fig5_4b_phi_year.csv"}</span>
<span id="cb6-477"><a href="#cb6-477" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Precision interaction model comparison</span><span class="co">](tables/fledging_precision_relLD_age_anova.csv)</span>{download="fledging_precision_relLD_age_anova.csv"}</span>
<span id="cb6-478"><a href="#cb6-478" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Precision interaction coefficient</span><span class="co">](tables/fledging_precision_relLD_age_interaction.csv)</span>{download="fledging_precision_relLD_age_interaction.csv"}</span>
<span id="cb6-479"><a href="#cb6-479" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Figure 5.4 simulation data</span><span class="co">](tables/fledging_zero_frequency_simulations.csv)</span>{download="fledging_zero_frequency_simulations.csv"}</span>
<span id="cb6-480"><a href="#cb6-480" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Conditional zero-frequency simulation data</span><span class="co">](tables/fledging_zero_frequency_conditional_simulations.csv)</span>{download="fledging_zero_frequency_conditional_simulations.csv"}</span>
<span id="cb6-481"><a href="#cb6-481" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Beta-binomial comparison</span><span class="co">](tables/fledging_bb_precision_comparison.csv)</span>{download="fledging_bb_precision_comparison.csv"}</span>
<span id="cb6-482"><a href="#cb6-482" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Zero-frequency diagnostic summary</span><span class="co">](tables/fledging_zero_frequency_summary.csv)</span>{download="fledging_zero_frequency_summary.csv"}</span>
<span id="cb6-483"><a href="#cb6-483" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Conditional zero-frequency diagnostic summary</span><span class="co">](tables/fledging_zero_frequency_conditional_summary.csv)</span>{download="fledging_zero_frequency_conditional_summary.csv"}</span>
<span id="cb6-484"><a href="#cb6-484" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Constant-phi simulation summary</span><span class="co">](tables/fledging_phi_temperature_constant_simulation_summary.csv)</span>{download="fledging_phi_temperature_constant_simulation_summary.csv"}</span>
<span id="cb6-485"><a href="#cb6-485" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Constant-phi simulation coefficients</span><span class="co">](tables/fledging_phi_constant_simulations.csv)</span>{download="fledging_phi_constant_simulations.csv"}</span>
<span id="cb6-486"><a href="#cb6-486" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Constant-phi histogram data</span><span class="co">](tables/figA_phi_constant_simulation.csv)</span>{download="figA_phi_constant_simulation.csv"}</span>
<span id="cb6-487"><a href="#cb6-487" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Temperature effect on phi conditional on brood survival</span><span class="co">](tables/fledging_phi_temperature_conditional_survival.csv)</span>{download="fledging_phi_temperature_conditional_survival.csv"}</span>
<span id="cb6-488"><a href="#cb6-488" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-489"><a href="#cb6-489" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Download the complete chapter script</span><span class="co">](R/30_fledging_chapter_models_figures.R)</span>{download="30_fledging_chapter_models_figures.R"}.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>